# これは例としての mods.toml ファイルです。Modのロードに関するデータが含まれています。
# 必須フィールドがいくつかあり (#mandatory)、他にもオプションのフィールドが多数あります (#optional)。
# 全体の形式は標準的な TOML フォーマット (v0.5.0) です。
# このファイルにはいくつかのTOMLリストが含まれていることに注意してください。
# TOML形式についての詳細は次を参照してください: https://github.com/toml-lang/toml
# ロードするModローダーの種類の名前です。通常のFML @Mod modsでは"javafml"と指定します。
modLoader="javafml" #mandatory
# 指定されたModローダーに一致するバージョン範囲 - 通常のFML @ModではForgeバージョンとなります
loaderVersion="${loader_version_range}" #mandatory これは通常、MinecraftのバージョンごとにForgeによって更新されます。バージョンのリストはダウンロードページを参照してください。
# あなたのModのライセンスです。これは必須のメタデータであり、再配布に関する性質を理解しやすくします。
# https://choosealicense.com/ でオプションを確認してください。「All rights reserved」はデフォルトの著作権主張であり、ここでもデフォルトになっています。
license="${mod_license}"
# このModに問題が発生した場合に参照するURL
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# Modのリスト - ここにいくつ許可されるかは個々のModローダーによって決まります。
[[mods]] #mandatory
# Modのmodid
modId="${mod_id}" #mandatory
# Modのバージョン番号
version="${mod_version}" #mandatory
# Modの表示名
displayName="${mod_name}" #mandatory
# このModのアップデートを確認するためのURL。JSONアップデート仕様については、https://docs.minecraftforge.net/en/latest/misc/updatechecker/ を参照してください。
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# このModの「ホームページ」を表示するためのURL。Mod UIに表示されます。
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# 表示のためのロゴを含むMod JARのルートにあるファイル名
#logoFile="examplemod.png" #optional
# Mod UIに表示されるテキストフィールド
#credits="" #optional
# Mod UIに表示されるテキストフィールド
authors="${mod_authors}" #optional
# 表示テストは、サーバー接続画面でのModの表示を制御します。
# MATCH_VERSION は、クライアントとサーバーのバージョンが異なる場合に赤いXが表示されることを意味します。これはデフォルトの動作であり、クライアントとサーバーの両方に要素があるModの場合に選択すべきです。
# IGNORE_SERVER_VERSION は、サーバーに存在していてもクライアントには存在しない場合に赤いXが表示されないことを意味します。これはサーバー専用Modの場合に使用すべきです。
# IGNORE_ALL_VERSION は、クライアントまたはサーバーに存在している場合に赤いXが表示されないことを意味します。これは特別なケースで、サーバーコンポーネントがないModにのみ使用すべきです。
# NONE は、Modに表示テストが設定されていないことを意味します。この場合は、IExtensionPoint.DisplayTestを参照し、自分でテストを定義する必要があります。どのようなスキームでもこの値で定義することができます。
# 重要な注意: これはModがどの環境（クライアントまたは専用サーバー）でロードされるかの指示ではありません。Modは見つかった場所でロードされ（場合によっては何もしません！）、動作するべきです。
#displayTest="MATCH_VERSION" # MATCH_VERSIONは指定されていない場合のデフォルトです (#optional)

# Modの説明テキスト（複数行!）(#mandatory)
description='''${mod_description}'''
# 依存関係 - 特定のmodidの依存関係を示すにはピリオド（.）を使用します。依存関係はオプションです。
[[dependencies.${mod_id}]] #optional
    # 依存関係のmodid
    modId="forge" #mandatory
    # この依存関係が存在する必要があるかどうか - 存在しない場合、以下で指定される順序付けが必要です
    mandatory=true #mandatory
    # 依存関係のバージョン範囲
    versionRange="${forge_version_range}" #mandatory
    # 依存関係のための順序関係 - BEFOREまたはAFTERは依存関係が必須でない場合に必要です
    # BEFORE - このModは依存関係よりも前にロードされます
    # AFTER - このModは依存関係の後にロードされます
    ordering="NONE"
    # この依存関係が適用される側面 - BOTH, CLIENT, またはSERVER
    side="BOTH"

# もう一つの依存関係
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    # このバージョン範囲は現在のMinecraftバージョンの最小値から、次のメジャーバージョンに含まれないものまでを宣言します
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# 特徴は、ゲーム環境の特定のプロパティであり、必要に応じて宣言することができます。この例では、
# ModにはGLバージョン3.2以上が必要であることを宣言しています。他の特徴も追加されます。
# これらはサイド対応であり、これを宣言してもModがサーバーでロードされるのを妨げることはありません。
#[features.${mod_id}]
#openGLVersion="[3.2,)"
